import Image from "next/image";
import {type Content,type Locale,links} from "@/content";
import Leaf from "./Leaf";
import MotionPreview from "./MotionPreview";
const sectionIds=["projects","experience","research","about"];
function Arrow({diagonal=false}:{diagonal?:boolean}){return <span aria-hidden="true" className="arrow">{diagonal?"↗":"↗"}</span>}
function Tags({items}:{items:string[]}){return <ul className="tags">{items.map(t=><li key={t}>{t}</li>)}</ul>}
function External({href,children,className=""}:{href:string;children:React.ReactNode;className?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>}
const publications = [
 {event:"32º SIICUSP",title:"ENXAME — Software para processamento de simulações gráficas acelerado em hardware para inteligência de sistemas auto-organizados e descentralizados",en:"ENXAME — Hardware-accelerated graphical simulations for self-organized, decentralized systems",authors:"Matheus Luis Oliveira da Silva · Eduardo do Valle Simões",url:"https://web.icmc.usp.br/SVAPAC/Distribui%C3%A7%C3%A3o%20dos%20trabalhos_siicusp%20-%20Per%C3%ADodo%20da%20Tarde.pdf"},
 {event:"31º SIICUSP",title:"Desenvolvimento da ferramenta ENXAME: simulador gráfico acelerado em hardware para modelos de swarm intelligence",en:"Developing ENXAME: a hardware-accelerated graphical simulator for swarm intelligence models",authors:"Matheus Luis Oliveira da Silva · Eduardo do Valle Simões",url:"https://web.icmc.usp.br/SVAPAC/cpq/SIICUSP/31%20SIICUSP/Distribui%C3%A7%C3%A3o%20dos%20trabalhos_siicusp%20-%20Per%C3%ADodo%20da%20Tarde.pdf"},
 {event:"28º SIICUSP · 2020",title:"Algoritmo evolutivo para posicionamento de sensores detectores de linha",en:"An evolutionary algorithm for positioning line-detecting sensors",authors:"Matheus Luis Oliveira da Silva",url:"https://web.icmc.usp.br/SVAPAC/cpq/SIICUSP/28%20SIICUSP/Trabalhos%2028%20SIICUSP%20-%20Sala%201%20%28manh%C3%A3%20e%20tarde%29%20-%20Alterado.pdf"},
 {event:"10º CONICT · 2019",title:"Desenvolvimento de Algoritmo Evolutivo para a identificação em simulação de locais adequados para o posicionamento de sensores em robôs seguidores de linha",en:"Developing an evolutionary algorithm to identify sensor positions in simulated line-following robots",authors:"Matheus Luis Oliveira Silva · Gustavo Voltani Von Atzingen · Márcio Kassouf Crocomo",url:"https://ocs.ifsp.edu.br/vi-conemac/xconict/schedConf/presentations"}
];
export default function Portfolio({lang,content:c}:{lang:Locale;content:Content}){
return <>
<a className="skip-link" href="#main">{c.skip}</a>
<header className="site-header"><div className="container header-inner">
 <a href={`/${lang}/`} className="brand" aria-label="MS Product Studio · Matheus Silva"><img src="/icon.svg" alt="" width="38" height="38"/><span><b>MS</b><span>PRODUCT STUDIO</span></span></a>
 <nav aria-label={lang==="pt"?"Navegação principal":"Main navigation"}>{c.nav.map((n,i)=><a href={`#${sectionIds[i]}`} key={n}>{n}</a>)}</nav>
 <div className="header-actions"><div className="language" aria-label={lang==="pt"?"Idioma":"Language"}><a href="/pt/" lang="pt-BR" hrefLang="pt-BR" aria-current={lang==="pt"?"page":undefined}>PT</a><span>/</span><a href="/en/" lang="en" hrefLang="en" aria-current={lang==="en"?"page":undefined}>EN</a></div><a href="#contact" className="header-contact">{c.contact} <Arrow/></a></div>
</div></header>
<main id="main">
<section className="hero container" id="top"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/>{c.eyebrow}</p><h1>{c.hero[0]}<br/>{c.hero[1]}<br/><em>{c.hero[2]}</em></h1><p className="hero-intro">{c.intro}</p><div className="hero-buttons"><a className="button" href="#projects">{c.heroCta}<span aria-hidden="true">↓</span></a><a className="text-link" href="#experience">{c.heroSecondary}<Arrow/></a></div><p className="hero-location"><span aria-hidden="true">◎</span>{c.location}</p></div><div className="hero-art"><Leaf/><div className="art-index"><span>MS / 001</span><span>ORGANIC SYSTEMS</span></div></div></section>
<div className="expertise-ribbon"><div className="container">{c.ribbon.map((r,i)=><span key={r}><i aria-hidden="true">{["⌘","↗","✳"][i]}</i>{r}</span>)}</div></div>
<section className="section container" id="projects"><div className="section-heading"><div><p className="eyebrow">{c.projectLabel}</p><h2>{c.projectTitle}</h2></div><p>{c.projectIntro}</p></div><div className="projects">{c.projects.map(p=><article className="project" key={p.id}><div className="project-media"><div className="media-topline"><span>{p.subtitle}</span><span aria-hidden="true">{p.number} / R&D</span></div>{p.media==="robots"?<MotionPreview src="/media/robots.mp4" poster="/media/robots.png" label={p.caption} play={c.play} pause={c.pause}/>:<div className="static-preview"><Image src="/media/ants-report.png" alt={p.caption} width={1366} height={768}/></div>}<p className="caption"><span className="status-dot"/>{p.caption}</p></div><div className="project-copy"><p className="eyebrow">{p.category}</p><h3>{p.title}</h3><p>{p.description}</p><Tags items={p.tags}/><details><summary>{c.details}<span aria-hidden="true">+</span></summary><p>{p.detail}</p><p className="credit">{p.credit}</p></details><External href={p.url} className="project-link">{c.code}<Arrow/></External></div></article>)}</div></section>
<section className="experience-section" id="experience"><div className="container section experience-layout"><div className="experience-heading"><p className="eyebrow">{c.experienceLabel}</p><h2>{c.experienceTitle}</h2><p>{c.experienceIntro}</p><span className="large-asterisk" aria-hidden="true">✳</span></div><div className="timeline">{c.experiences.map((e,i)=><article className="job" key={e.name}><div className="job-marker" aria-hidden="true">{String(i+1).padStart(2,"0")}</div><p className="eyebrow date">{e.date}</p><h3>{e.name}</h3><h4>{e.role}</h4><p>{e.text}</p>{e.extra&&<p>{e.extra}</p>}<Tags items={e.tags}/></article>)}</div></div><div className="container other-work"><h3>{c.moreTitle}</h3><div>{c.more.map(m=><article key={m.title}><p className="eyebrow">{m.date}</p><h4>{m.title}</h4><p>{m.text}</p></article>)}</div></div></section>
<section className="container section" id="research"><div className="section-heading"><div><p className="eyebrow">{c.researchLabel}</p><h2>{c.researchTitle}</h2></div><p>{c.researchIntro}</p></div><div className="publications">{publications.map((p,i)=><article className="publication" key={p.event}><div className="publication-meta"><span>{p.event}</span><small>{i===3?c.conictType:c.researchType}</small></div><div><h3><External href={p.url}>{lang==="pt"?p.title:p.en}</External></h3>{lang==="en"&&<p lang="pt-BR" className="original-title">{p.title}</p>}<p>{p.authors}{i<2?(lang==="pt"?" (orientador)":" (supervisor)"):""}</p></div><External className="publication-arrow" href={p.url}><span className="sr-only">{c.source}: {p.event}</span><Arrow/></External></article>)}</div><External className="report-link" href="https://github.com/msproductstudio/Hardware-Accelerated-Ant-Colony-Based-Swarm-System/blob/main/Documentation/PUB1/Relat%C3%B3rio%20FInal%20.pdf"><span className="report-icon" aria-hidden="true">↳</span><div><p className="eyebrow">{c.report}</p><h3>{c.reportTitle}</h3><p>{c.reportAuthors}</p></div><Arrow/></External></section>
<section className="about-section" id="about"><div className="container section"><div className="about-grid"><div><p className="eyebrow">{c.aboutLabel}</p><h2>{c.aboutTitle}</h2><p className="about-lead">{c.aboutText}</p><p>{c.aboutText2}</p><div className="profile-links"><External href={links.linkedin}>LinkedIn <Arrow/></External><External href={links.lattes}>Lattes <Arrow/></External><External href={links.personalGithub}>GitHub <Arrow/></External></div></div><aside className="studio-card"><div className="studio-mark" aria-hidden="true"><img src="/icon.svg" width="64" height="64" alt=""/><span>MS<br/><small>PRODUCT STUDIO</small></span></div><h3>{c.studioTitle}</h3><p>{c.studioText}</p><External href={links.github}>github.com/msproductstudio <Arrow/></External></aside></div><div className="education"><h3>{c.educationTitle}</h3><div>{c.education.map(e=><article key={e.school}><p className="eyebrow">{e.date}</p><h4>{e.school}</h4><p>{e.course}</p><small>{e.note}</small></article>)}</div></div><div className="skills"><h3>{c.skillsTitle}</h3><div>{c.skillGroups.map(g=><article key={g.name}><h4>{g.name}</h4><Tags items={g.items}/></article>)}</div></div><div className="beyond"><h3>{c.beyondTitle}</h3><div>{c.beyond.map(b=><article key={b.title}><h4>{b.title}</h4><p>{b.text}</p></article>)}</div></div></div></section>
<section className="contact-section container section" id="contact"><div><p className="eyebrow">{c.contactLabel}</p><h2>{c.contactTitle}</h2><p>{c.contactText}</p><a className="button" href={links.email}>{c.emailLabel}<Arrow/></a></div><div className="contact-links"><External href={links.linkedin}>LinkedIn <Arrow/></External><External href={links.github}>GitHub <Arrow/></External><External href={links.lattes}>Lattes <Arrow/></External><a href={links.email}>matheusluisosilva@gmail.com <Arrow/></a></div></section>
</main><footer className="container footer"><div><p>{c.footer}</p><small>{c.rights}</small></div><a href="#top">{c.back} <span aria-hidden="true">↑</span></a></footer>
</>;
}
