export type Locale = "pt" | "en";
const repos = {ants:"https://github.com/msproductstudio/Hardware-Accelerated-Ant-Colony-Based-Swarm-System",robots:"https://github.com/msproductstudio/Evolutionary-Algorithm-and-Following-Line-Robots-Simulation"};
export const links = {github:"https://github.com/msproductstudio",personalGithub:"https://github.com/matheuslosilva",linkedin:"https://www.linkedin.com/in/matheuslosilva/",lattes:"http://lattes.cnpq.br/1199400949344072",email:"mailto:matheusluisosilva@gmail.com"};
export const copy = {
pt: {
 description:"Matheus Silva: engenharia de software, sistemas distribuídos e computação inspirada na natureza. Conheça minha trajetória, projetos e pesquisa.",
 nav:["Projetos","Trajetória","Pesquisa","Sobre"],contact:"Vamos conversar",skip:"Pular para o conteúdo",
 eyebrow:"MATHEUS SILVA / ENGENHEIRO DE SOFTWARE",
 hero:["Ideias com raízes.","Sistemas que","evoluem."],
 intro:"Da inteligência de enxames a plataformas digitais. Construo software conectando pesquisa, arquitetura e cuidado com o produto.",
 heroCta:"Explore meus projetos",heroSecondary:"Conheça minha trajetória",location:"BRASIL · CONSTRUINDO COM PROPÓSITO",
 ribbon:["Engenharia de software","Sistemas distribuídos","Computação bioinspirada"],
 projectLabel:"01 / PROJETOS SELECIONADOS",projectTitle:"Curiosidade que vira código.",projectIntro:"Dois projetos de pesquisa explorando como regras simples podem dar origem a comportamentos complexos.",
 code:"Explorar código",details:"Por dentro do projeto",play:"Reproduzir captura",pause:"Pausar captura",
 projects:[
 {id:"ants",number:"01",category:"INTELIGÊNCIA DE ENXAMES",title:"Inteligência coletiva, em movimento.",subtitle:"Ant Colony · ENXAME",description:"Um ambiente para investigar busca e coleta de objetos com agentes inspirados em colônias de formigas. Comportamentos locais, feromônios e organização coletiva se encontram em uma simulação visual.",tags:["C++","OpenGL","GLFW","Dear ImGui"],url:repos.ants,media:"ants",caption:"Imagem original · relatório PUB/USP, figura 2",detail:"A versão atual usa C++ para a simulação e OpenGL para visualização, com GLFW, GLM e controles Dear ImGui. A pesquisa de 2021–2024 também investigou CUDA e otimização evolutiva; o Makefile atual não compila kernels CUDA. Parâmetros do experimento são carregados de JSON.",credit:"Imagem: figura 2 do relatório PUB/USP de Matheus Luis Oliveira da Silva. Orientação: Eduardo do Valle Simões. Histórico e colaborações preservados no repositório, incluindo GeorgeGantus e simoesusp."},
 {id:"robots",number:"02",category:"ROBÓTICA EVOLUTIVA",title:"Aprender a encontrar o caminho.",subtitle:"Line-following robots",description:"Onde posicionar os sensores de um robô seguidor de linha? Uma simulação explora a pergunta usando seleção, cruzamento e mutação para evoluir as posições de três sensores.",tags:["Python","Pygame","Algoritmos evolutivos"],url:repos.robots,media:"robots",caption:"Captura real · Python/Pygame no Ubuntu · 14 s",detail:"Uma população de 40 configurações é avaliada por checkpoints, voltas, saída da pista e loops. O algoritmo preserva o melhor indivíduo e gera novas configurações por cruzamento e mutação. O vídeo registra os métodos originais da simulação, sem recriar seu comportamento no site.",credit:"Código: Matheus Luis Oliveira da Silva. Trabalho apresentado no CONICT com Gustavo Voltani Von Atzingen e Márcio Kassouf Crocomo; apresentado também no 28º SIICUSP."}
 ],
 experienceLabel:"02 / TRAJETÓRIA",experienceTitle:"Da arquitetura à entrega.",experienceIntro:"Experiência em produtos digitais, jogos, serviços financeiros e infraestrutura em nuvem.",
 experiences:[
 {name:"NationGG",role:"Engenheiro de software · Membro fundador",date:"OUT 2025 — ATUAL",text:"Liderança de desenvolvimento em uma equipe de 10 pessoas, ao lado do CTO, na arquitetura de uma plataforma social para gamers. Topologia de mais de 25 serviços Go, infraestrutura em AWS e Kubernetes e comunicação entre serviços.",extra:"Chat em tempo real, moderação, analytics, autenticação JWT/OAuth2 e processamento de conteúdo com IA.",tags:["Go","Kafka","gRPC","SSE","AWS","Terraform"]},
 {name:"Afterverse",role:"Engenheiro de software",date:"SET 2024 — JAN 2026",text:"Desenvolvimento backend em Kotlin para servidores de jogos de alto desempenho. Trabalho com DynamoDB e serviços AWS, com pipelines e operações em Jenkins, Rancher e Argo.",extra:"Experiência em uma empresa de jogos com alcance internacional.",tags:["Kotlin","DynamoDB","AWS","CI/CD"]},
 {name:"XP Inc.",role:"Estágio em engenharia de software",date:"AGO 2023 — SET 2024",text:"Integrante da equipe de cadastro de clientes, com 10 engenheiros. Desenvolvimento e suporte a sistemas backend para uma base de mais de 3 milhões de clientes.",extra:"",tags:["C++","PostgreSQL"]},
 {name:"AnimallTAG",role:"Estágio em engenharia de software",date:"MAI 2023 — AGO 2023",text:"Modelagem e implementação do banco MySQL do SisGado, sistema de gestão pecuária. Desenvolvimento backend e frontend e definição da arquitetura de infraestrutura AWS.",extra:"",tags:["PHP","Laravel","MySQL","AWS"]},
 {name:"Opus Software",role:"Estágio em computação em nuvem",date:"SET 2022 — ABR 2023",text:"Criação de materiais técnicos e projetos práticos de sistemas com Docker, Kubernetes e AWS. Alinhamentos semanais e apresentações de projetos a cada dois meses.",extra:"",tags:["Docker","Kubernetes","AWS"]}
 ],
 moreTitle:"Outras construções",more:[
 {title:"Mein · Finanças pessoais",date:"FEV — DEZ 2025",text:"Cofundação e engenharia de um aplicativo financeiro. Coordenação de 2 desenvolvedores e 1 designer, arquitetura, planejamento de sprints, revisões de código e entregas. Kotlin Multiplatform para Android/iOS, backend Kotlin, PostgreSQL, AWS e Terraform."},
 {title:"SEAME · Tecnologia com impacto social",date:"JAN — DEZ 2019",text:"Liderança de um grupo no desenvolvimento de uma ferramenta para uma instituição de apoio a jovens em vulnerabilidade socioeconômica. Contato com a equipe da instituição e desenvolvimento em C# e Visual Studio."}
 ],
 researchLabel:"03 / PESQUISA E PUBLICAÇÕES",researchTitle:"Investigar. Experimentar. Compartilhar.",researchIntro:"Minha pesquisa conecta robótica, inteligência de enxames e algoritmos evolutivos. Entre 2021 e 2024, desenvolvi simulações no ICMC-USP e coordenei dois bolsistas na implementação de novas funcionalidades.",
 source:"Ver registro",report:"Relatório de pesquisa · PUB/USP",reportTitle:"Busca e resgate baseado em inteligência de grandes enxames acelerados em hardware",reportAuthors:"Matheus Luis Oliveira da Silva · Orientador: Eduardo do Valle Simões",
 researchType:"Apresentação em simpósio",conictType:"Trabalho em congresso",
 aboutLabel:"04 / SOBRE MIM",aboutTitle:"Engenharia com olhar humano.",aboutText:"Sou Matheus Silva, bacharel em Ciência da Computação pela USP. Gosto de entender como as coisas funcionam — e transformar esse entendimento em produtos que fazem sentido para as pessoas.",
 aboutText2:"Fora do código, o teatro acompanha minha formação desde 2016: escrita, expressão, escuta e trabalho em grupo também fazem parte da maneira como construo software.",
 studioTitle:"Um novo espaço para construir.",studioText:"MS Product Studio é minha iniciativa recém-criada. É por aqui que passarei a conduzir e compartilhar meus projetos, reunindo engenharia, pesquisa e desenvolvimento de produtos.",
 educationTitle:"Formação",education:[{school:"Universidade de São Paulo",course:"Bacharelado em Ciência da Computação · ICMC",date:"2020 — 2025",note:"Média acadêmica: 8,7 / 10"},{school:"Instituto Federal de São Paulo",course:"Formação técnica em Informática · Piracicaba",date:"2016 — 2019",note:"Cofundador e integrante do grupo de teatro da instituição."}],
 skillsTitle:"Ferramentas do meu trabalho",skillGroups:[{name:"Linguagens e produto",items:["Go","Kotlin","Kotlin Multiplatform","C++","Python","React / Next.js","PHP / Laravel","C#"]},{name:"Dados e comunicação",items:["PostgreSQL","DynamoDB","Redis","MySQL","Kafka","gRPC / Protobuf","SSE"]},{name:"Arquitetura e entrega",items:["Microsserviços","Sistemas orientados a eventos","AWS","Docker","Kubernetes","Terraform","GitHub Actions","Jenkins","Rancher","Argo","Desenvolvimento assistido por IA"]}],
 beyondTitle:"Além do código",beyond:[{title:"PET Codifique",text:"Tutor de lógica de programação e JavaScript para cerca de 200 estudantes do ensino médio, em parceria com outro tutor. Mai 2021 — jan 2022."},{title:"OBMEP",text:"Ouro em 2015, prata em 2013, bronze em 2012 e menção honrosa em 2016."},{title:"Idiomas",text:"Português brasileiro nativo · Inglês intermediário."}],
 contactLabel:"05 / CONTATO",contactTitle:"Vamos construir a próxima ideia?",contactText:"Para falar sobre software, pesquisa ou um novo projeto, entre em contato.",emailLabel:"Me envie um e-mail",footer:"Matheus Silva · MS Product Studio",back:"Voltar ao início",rights:"Feito com intenção. Em constante evolução."
},
en: {
 description:"Matheus Silva: software engineering, distributed systems and nature-inspired computing. Explore my experience, projects and research.",
 nav:["Projects","Experience","Research","About"],contact:"Let's talk",skip:"Skip to content",
 eyebrow:"MATHEUS SILVA / SOFTWARE ENGINEER",
 hero:["Ideas take root.","Systems","evolve."],
 intro:"From swarm intelligence to digital platforms. I build software by connecting research, architecture and thoughtful product development.",
 heroCta:"Explore my projects",heroSecondary:"Discover my experience",location:"BRAZIL · BUILDING WITH PURPOSE",
 ribbon:["Software engineering","Distributed systems","Bio-inspired computing"],
 projectLabel:"01 / SELECTED PROJECTS",projectTitle:"Curiosity, translated into code.",projectIntro:"Two research projects exploring how simple rules can give rise to complex behavior.",
 code:"Explore the code",details:"Inside the project",play:"Play recording",pause:"Pause recording",
 projects:[
 {id:"ants",number:"01",category:"SWARM INTELLIGENCE",title:"Collective intelligence in motion.",subtitle:"Ant Colony · ENXAME",description:"An environment for studying object search and collection with agents inspired by ant colonies. Local behaviors, pheromones and collective organization meet in a visual simulation.",tags:["C++","OpenGL","GLFW","Dear ImGui"],url:repos.ants,media:"ants",caption:"Original image · PUB/USP research report, figure 2",detail:"The current version uses C++ for simulation and OpenGL for visualization, with GLFW, GLM and Dear ImGui controls. The 2021–2024 research also explored CUDA and evolutionary optimization; the current Makefile does not compile CUDA kernels. Experiment parameters are loaded from JSON.",credit:"Image: figure 2 of the PUB/USP report by Matheus Luis Oliveira da Silva. Supervisor: Eduardo do Valle Simões. Repository history and collaborations are preserved, including GeorgeGantus and simoesusp."},
 {id:"robots",number:"02",category:"EVOLUTIONARY ROBOTICS",title:"Learning to find the way.",subtitle:"Line-following robots",description:"Where should a line-following robot's sensors be placed? A simulation explores this question through selection, crossover and mutation, evolving the positions of three sensors.",tags:["Python","Pygame","Evolutionary algorithms"],url:repos.robots,media:"robots",caption:"Real capture · Python/Pygame on Ubuntu · 14 s",detail:"A population of 40 configurations is evaluated through checkpoints, completed laps, track departures and loops. The algorithm preserves its best individual and generates new configurations using crossover and mutation. The recording runs the original simulation methods; its behavior is not recreated on this website.",credit:"Code: Matheus Luis Oliveira da Silva. CONICT work with Gustavo Voltani Von Atzingen and Márcio Kassouf Crocomo; also presented at the 28th SIICUSP."}
 ],
 experienceLabel:"02 / EXPERIENCE",experienceTitle:"From architecture to delivery.",experienceIntro:"Experience across digital products, games, financial services and cloud infrastructure.",
 experiences:[
 {name:"NationGG",role:"Software Engineer · Founding Member",date:"OCT 2025 — PRESENT",text:"Leading development in a team of 10, working with the CTO on the architecture of a social platform for gamers. A topology of 25+ Go services, AWS and Kubernetes infrastructure, and cross-service communication.",extra:"Real-time chat, moderation, analytics, JWT/OAuth2 authentication and AI-powered content processing.",tags:["Go","Kafka","gRPC","SSE","AWS","Terraform"]},
 {name:"Afterverse",role:"Software Engineer",date:"SEP 2024 — JAN 2026",text:"Kotlin backend development for high-performance game servers. Working with DynamoDB and AWS services, with pipelines and operations in Jenkins, Rancher and Argo.",extra:"Experience at a game company with an international audience.",tags:["Kotlin","DynamoDB","AWS","CI/CD"]},
 {name:"XP Inc.",role:"Software Engineering Intern",date:"AUG 2023 — SEP 2024",text:"Member of a 10-engineer customer registration team. Developing and supporting backend systems serving more than 3 million customers.",extra:"",tags:["C++","PostgreSQL"]},
 {name:"AnimallTAG",role:"Software Engineering Intern",date:"MAY 2023 — AUG 2023",text:"Designed and built the MySQL database for SisGado, a livestock management system. Developed the backend and frontend and defined its AWS infrastructure architecture.",extra:"",tags:["PHP","Laravel","MySQL","AWS"]},
 {name:"Opus Software",role:"Cloud Computing Intern",date:"SEP 2022 — APR 2023",text:"Created technical materials and practical system designs using Docker, Kubernetes and AWS. Weekly team discussions and project presentations every two months.",extra:"",tags:["Docker","Kubernetes","AWS"]}
 ],
 moreTitle:"Other things I've built",more:[
 {title:"Mein · Personal finance",date:"FEB — DEC 2025",text:"Co-founded and engineered a personal finance app. Coordinated 2 developers and 1 designer, architecture, sprint planning, code reviews and delivery. Kotlin Multiplatform for Android/iOS, a Kotlin backend, PostgreSQL, AWS and Terraform."},
 {title:"SEAME · Technology for social impact",date:"JAN — DEC 2019",text:"Led a development group building a tool for an institution supporting young people in socioeconomic vulnerability. Worked with the institution's staff and developed with C# and Visual Studio."}
 ],
 researchLabel:"03 / RESEARCH & PUBLICATIONS",researchTitle:"Investigate. Experiment. Share.",researchIntro:"My research connects robotics, swarm intelligence and evolutionary algorithms. Between 2021 and 2024, I developed simulations at ICMC-USP and coordinated two scholarship students implementing new features.",
 source:"View record",report:"Research report · PUB/USP",reportTitle:"Search and rescue based on large hardware-accelerated intelligent swarms",reportAuthors:"Matheus Luis Oliveira da Silva · Supervisor: Eduardo do Valle Simões",
 researchType:"Symposium presentation",conictType:"Conference contribution",
 aboutLabel:"04 / ABOUT ME",aboutTitle:"Engineering with a human perspective.",aboutText:"I'm Matheus Silva, a Computer Science graduate from the University of São Paulo. I enjoy understanding how things work — and turning that understanding into products that make sense for people.",
 aboutText2:"Beyond code, theater has been part of my life since 2016. Writing, expression, listening and teamwork also shape the way I build software.",
 studioTitle:"A new space to build.",studioText:"MS Product Studio is my newly created initiative. It is where I will develop and share my projects, bringing together engineering, research and product development.",
 educationTitle:"Education",education:[{school:"University of São Paulo",course:"BSc in Computer Science · ICMC",date:"2020 — 2025",note:"GPA: 8.7 / 10"},{school:"Federal Institute of São Paulo",course:"Technical education in Information Technology · Piracicaba",date:"2016 — 2019",note:"Co-founder and member of the institution's theater group."}],
 skillsTitle:"Tools of my trade",skillGroups:[{name:"Languages & product",items:["Go","Kotlin","Kotlin Multiplatform","C++","Python","React / Next.js","PHP / Laravel","C#"]},{name:"Data & communication",items:["PostgreSQL","DynamoDB","Redis","MySQL","Kafka","gRPC / Protobuf","SSE"]},{name:"Architecture & delivery",items:["Microservices","Event-driven systems","AWS","Docker","Kubernetes","Terraform","GitHub Actions","Jenkins","Rancher","Argo","AI-assisted development"]}],
 beyondTitle:"Beyond code",beyond:[{title:"PET Codifique",text:"Taught programming logic and JavaScript to around 200 high school students alongside a fellow tutor. May 2021 — Jan 2022."},{title:"OBMEP",text:"Brazilian Public School Mathematics Olympiad: gold in 2015, silver in 2013, bronze in 2012 and honorable mention in 2016."},{title:"Languages",text:"Native Brazilian Portuguese · Intermediate English."}],
 contactLabel:"05 / CONTACT",contactTitle:"Let's build the next idea.",contactText:"To talk about software, research or a new project, get in touch.",emailLabel:"Send me an email",footer:"Matheus Silva · MS Product Studio",back:"Back to top",rights:"Made with intention. Always evolving."
}
};
export type Content = typeof copy.pt;
